# website settings
website:
  title: "Margarita Tsakiridou"
  description: "Data Analyst/Scientist"
  image: img/my_image.jpg
  
  favicon: img/test.jpg
  
  # start of the navigation bar at the top of the website
  navbar:
    left:
      - text: "CV"
        href: cv/index.qmd
    
    # your social media handles
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/margaritatsakiridou/
      - icon: envelope
        aria-label: email
        href: "mailto:margarita.tsakiridou@outlook.com"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer:
    center: "Margarita Tsakiridou" 

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true